version: '3'

services:
  php:
    image: prooph/php:7.2-cli
    volumes:
      - ./../../:/app
    command: tail -f /dev/null

  eventstore:
    image: eventstore/eventstore:release-5.0.1
    ports:
      - 2113:2113
      - 1113:1113
    volumes:
      - "~/Data/eventstorenode/node1:/var/lib/eventstore"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:2113/stats || exit 1"]
      interval: 5s
      timeout: 2s
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=all
